name: Deploy to GitHub Pages

on:
  # Trigger on push to main branch
  push:
    branches: [ main ]
    paths:
      - 'public/gallery/**'  # Trigger when gallery images change
      - 'src/**'             # Trigger when source code changes
  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Process images
        run: |
          # Create gallery directory if it doesn't exist
          mkdir -p public/gallery

      - name: Debug before build
        run: |
          echo "Current directory:"
          pwd
          echo "Files before build:"
          ls -la

      - name: Build
        run: |
          echo "Starting build process..."
          npm run build
          echo "Build completed"

      - name: Debug after build
        run: |
          echo "Files after build:"
          ls -la
          echo "All directories:"
          find . -type d

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1